name = "sep-web"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "sep-web-db"
database_id = "0fab311a-138f-48e3-a581-d451d4da2258"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "placeholder-run-wrangler-kv-create"
